# Generated by Django 4.2.6 on 2023-10-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_frontend', models.PositiveIntegerField()),
                ('years_backend', models.PositiveIntegerField()),
                ('satisfied_customers', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfoto', models.ImageField(upload_to='images/')),
                ('name', models.TextField(blank=True, max_length=100, null=True)),
                ('position', models.TextField(blank=True, max_length=200, null=True)),
                ('aboutme', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='social_media_images/')),
            ],
        ),
    ]
