# Generated by Django 4.2.6 on 2023-10-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='myfoto',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/social_media_images/'),
        ),
    ]
